### ISSUE TITLE
parameter settings when setting up from ssh, but accessing browser locally

### ISSUE THREAD

**Issue by LisaSikkema** [Novartis/cellxgene-gateway#21]
Hi cellxgene-gateway team,

I'd like to host a cellxgene server that can be accessed by anyone. I'm working from a secure server and I'm not super computer savvy, is there any chance you guys could specify a few of the parameters "for dummies"? Specifically:

EXTERNAL_HOST: this should be the host name of my secure server if I understand correctly, and how do I know which port to use?
GATEWAY_IP - the command socket.gethostbyname(socket.gethostname()) doesn't seem to work for me, is there any other way to find the IP address?
GATEWAY_PORT: how do I know what this should be?

Any help would be greatly appreciated! And really cool that you guys set this up. 

Best,
Lisa

**Comment by alokito** [comment]
Hi Lisa! Thanks for taking a look at cellxgene gateway. First, you only need it if you are planning to host multiple datasets, otherwise you can run cellxgene directly. As for your questions:

EXTERNAL_HOST: This should be the host name that the users will type into a web browser. You can leave off the port if you are using the default port for the EXTERNAL_PROTOCOL, i.e. port 80 for http or port 443 for https.
GATEWAY_IP: as noted in the instructions, this is used to display help on uploading data, and you can leave it as 127.0.0.1 for now. It should really be optional. I'd like to make it easier to not show these instructions at all for public servers; right now you need to edit the templates inside the package. I'm not sure if there's an easier way to override flask templates, but perhaps I should reach out to the flask team for advice.
GATEWAY_PORT: This determines what port cellxgene-gateway will listen on, and depends greatly on how your internal networking is set up. For example, do you have nginx or squid or some other kind of proxy or load balancer between cellxgene-gateway and the internet? If so then the port should be whatever the backend port of that network appliance is set to. For the simple case where web browsers will be connecting directly to cellxgene-gateway (i.e. your secure server is directly accessible from the internet), it should be the same as the EXTERNAL_HOST port, which in the simplest case would be port 80 for http.

Hope this helps, and feel free to post a link to your site if it's publicly accessible and okay to share.

**Comment by LisaSikkema** [comment]
Hi alokito,
Thanks a lot for your quick reply! I actually do not need to host multiple datasets, but I'm hoping to host a dataset for multiple users simultaneously, and thought that I needed your software for this. I'll take another look at the cellxgene website, seems like I misunderstood. Thanks again!

**Comment by alokito** [comment]
Hi Lisa! I presume you found what you needed, and will close this ticket.
