### ISSUE TITLE
local nested subdirectories

### ISSUE THREAD

**Issue by Jon-bioinfo** [Novartis/cellxgene-gateway#50]
Previously I could have subdirectories in cellxgene_data/ and linking to the subdirectory would only show the h5ad files in that subdirectory. But after updating beyond 0.2.3 clicking into a subdirectory is still showing the full filecrawl for all subdirectories?

<img width="601" alt="Screen Shot 2021-07-16 at 19 34 29" src="https://user-images.githubusercontent.com/40158588/125935045-27276772-326e-4475-9509-7d3e2645f9fd.png">

Here I have clicked on 01, but it still shows the files for 02/ etc...

**Comment by alokito** [comment]
Thanks for reporting this. It is definitely a bug, and most likely one that can be quickly fixed. I can only say two things

1. We have started adding automated tests, and will add a regression test for this.
2. I guess this functionality is not being used much internally, or was somehow misunderstood.

**Comment by alokito** [comment]
Hi @Jon-bioinfo  this should be fixed in 0.3.6, please confirm. I also noticed some changes in arguments expected by cellxgene 0.17.0 which will likely require some changes in cellxgene-gateway... to preserve similar behavior to 0.16.0 it may be a good idea to disable gene sets saving with:

export CELLXGENE_ARGS="--disable-gene-sets-save"

Otherwise users will be prompted for a filename each time, and the gene sets will be saved to the current working directory of cellxgene (not the location of the data files). This is kind of useless; I probably need to rethink how cellxgene-gateway should interact the cellxgene flags in light of these changes.

**Comment by Jon-bioinfo** [comment]
Thanks, looks good. I had noticed the gene sets dialog as well but that flag solves the immediate issue.
