### ISSUE TITLE
The filename, directory name, or volume label syntax is incorrect.

### ISSUE THREAD

**Issue by maarten-hifibio** [Novartis/cellxgene-gateway#54]
Hi,

I installed cellxgene-gateway in its own conda environment on Windows 10.
After I try to run `cellxgene-gateway`, all the .h5ad files show up in the file crawler.
However, clicking any one of them gives me the following error:

![image](https://user-images.githubusercontent.com/85952880/135286944-e384ea28-5a91-48a0-a0af-bc52d23c9cb3.png)

This is the output in the terminal:

`2021-09-29 10:00:18,469:werkzeug:INFO: * Running on http://0.0.0.0:5005/ (Press CTRL+C to quit)
2021-09-29 10:00:24,521:werkzeug:INFO:127.0.0.1 - - [29/Sep/2021 10:00:24] "←[37mGET / HTTP/1.1←[0m" 200 -
2021-09-29 10:00:26,100:werkzeug:INFO:127.0.0.1 - - [29/Sep/2021 10:00:26] "←[37mGET /filecrawl.html HTTP/1.1←[0m" 200 -
view path=My_AnnData.h5ad/, source_name=None, dataset=Z:\AnnData\My_AnnData.h5ad, annotation_file= None, key=My_AnnData.h5ad, source=local`

`2021-09-29 10:00:30,877:cellxgene_gateway:INFO:launching yes | C:\foobarbaz\anaconda3\envs\cellbygene-gateway\Scripts\cellxgene.exe launch Z:\AnnData\My_AnnData.h5ad --port 8000 --host 127.0.0.1 --disable-annotations `

`Exception in thread Thread-6:
Traceback (most recent call last):
  File "c:\foobarbaz\anaconda3\envs\cellbygene-gateway\lib\threading.py", line 926, in _bootstrap_inner
    self.run()
  File "c:\foobarbaz\anaconda3\envs\cellbygene-gateway\lib\threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "c:\foobarbaz\anaconda3\envs\cellbygene-gateway\lib\site-packages\cellxgene_gateway\subprocess_backend.py", line 82, in launch
    raise ProcessException.from_cache_entry(cache_entry)
cellxgene_gateway.process_exception.ProcessException`

These are my conda environment variables

`CELLXGENE_DATA = Z:\AnnData`
`CELLXGENE_LOCATION = C:\foobarbaz\anaconda3\envs\cellbygene-gateway\Scripts\cellxgene.exe`

This error happened already yesterday, when I was able to run `cellxgene launch My_AnnData.h5ad` successfully. The problem seems therefore unrelated to today's cellxgene bug. 
To confirm: `conda env config vars set CELLXGENE_ARGS=--no-upgrade-check` also does not solve the problem.
Any suggestions would be appreciated!

**Comment by alokito** [comment]
Hello! Thanks for reaching out. I have access to a windows machine, but I have only run cellxgene-gateway in WSL2. I may not have too much time to look into this until the weekend. In the meanwhile, the error indicates that cellxgene-gateway is having trouble launching cellxgene. It launches using subprocess.Popen as you can see on [line 59 of subprocess_backend.py](https://github.com/Novartis/cellxgene-gateway/blob/620181ae4d2ae10eddcf960e081a4f564a0a13ef/cellxgene_gateway/subprocess_backend.py#L59). Fortunately, it logs the launch command immediately before executing it:
```
yes | C:\foobarbaz\anaconda3\envs\cellbygene-gateway\Scripts\cellxgene.exe launch Z:\AnnData\My_AnnData.h5ad --port 8000 --host 127.0.0.1 --disable-annotations
```
What happens if you run this command directly in the windows shell? (not sure which shell Popen picks on windows)
