### ISSUE TITLE
Customizations to the UI

### ISSUE THREAD

**Issue by tkakar** [Novartis/cellxgene-gateway#79]
Thank you for developing the cellxgene-gateway, it seems pretty convenient.

I'm following the docs to customize the UI by changing the styles/html files. When I run the ` run.sh.example` I can see my changes. But dockerizing it using the provided docker file does not show changes, probably it uses the installed version of the cellxgene-gateway using `RUN pip install cellxgene-gateway 'MarkupSafe<2.1'`?. 

I'm unable to make it work properly using the development guidelines.
Executing `setup.py` throws error.
`Processing dependencies for cellxgene-gateway==0.3.10
Searching for certifi>=2017.4.17
Reading https://pypi.org/simple/certifi/
Download error on https://pypi.org/simple/certifi/: unknown url type: https -- Some packages may not be found!
Couldn't find index page for 'certifi' (maybe misspelled?)
Scanning index of all packages (this may take a while)
Reading https://pypi.org/simple/
Download error on https://pypi.org/simple/: unknown url type: https -- Some packages may not be found!
No local packages or working download links found for certifi>=2017.4.17
error: Could not find suitable distribution for Requirement.parse('certifi>=2017.4.17')`

Is anyone experiencing similar issue? How can I make docker container read the changes? Or run it in the develop mode without the run.sh.example file?  
Appreciate your help.

**Comment by alokito** [comment]
Hi @tkakar ! You are correct that `pip install cellxgene-gateway` will use the published version of cellxgene-gateway from PyPI, not the one in the local folder. I would actually recommend customizing this version within the dockerfile rather than checking out the repo and customizing it here. You can see an example of this here: https://github.com/Novartis/cellxgene-gateway/tree/79_add_docker_example/examples/customized_docker_image hope it helps!

**Comment by tkakar** [comment]
@alokito Thank you, this worked perfectly!

**Comment by alokito** [comment]
This is merged into master, please open a new ticket if there are any remaining issues.
